"""Shared logic for the example-based integration runner.

Single source of truth imported by:
    - conftest.pytest_generate_tests  (case discovery at collection time)
    - tests/test_integration.py       (running + comparing, plus harness self-tests)

Example folder structure (fixed):

    examples/
      <example-name>/                  ← one "case" == one generate_report call
        expected_output.json           ← generated by --update-expected (see below)
        sub-<id>/
          [ses-<id>/]                  ← optional session level
            perf/
              *_asl.json      (required: defines an acquisition)
              *_asl.nii[.gz]  (required: >= 1 per case; only its slice count is read)
              *_m0scan.json   (optional)
              *_aslcontext.tsv(optional)

A CASE is any immediate child of examples/ with at least one *_asl.json inside a
folder named ``perf``. Discovery keys on inputs, NOT on expected_output.json, so
``--update-expected`` can bootstrap a case that has no golden yet. A case may hold
several acquisitions (multiple subjects/sessions/runs); the tool consolidates them
into one consistency report. Only files inside ``perf`` are considered; anat/,
fmap/, derivatives/ and sourcedata/ are ignored.

ASL <-> M0/TSV pairing (per perf folder), following the mentors' rules. The tool
pairs sidecars to an ASL purely by ORDER in the flat file list, so the runner emits
each acquisition as asl -> m0 -> tsv and decides the pairing itself:

    * exactly matching prefixes (e.g. sub-01_run-1)      -> pair directly
    * an ASL with no prefix-matched sidecar              -> reuse a FALLBACK sidecar
      (the one with the latest creation time, tie-broken by filename), which covers
      both "more ASL than M0: reuse the shared M0 for all unmatched" and
      "more M0 than ASL: use the latest M0". A repeated M0 path in the list is fine
      (verified: the tool re-reads it and pairs it to each ASL).

Every fallback emits a ``PairingFallbackWarning`` (visible in pytest's warnings
summary) so the person running --update-expected can review the decision before
committing the golden.

NOTE ON "latest creation time": Linux has no true birth time (st_birthtime is
absent; st_ctime is metadata-change time), and git does not preserve timestamps, so
in a fresh clone all files share ~one time. The filename tie-break therefore
dominates for committed examples (deterministic in CI), while real creation time is
honoured locally when it is meaningful. The fallback only fires when prefixes don't
match, which is rare.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path
from typing import Any, Optional

from pyaslreport import generate_report
from pyaslreport.enums import ModalityTypeValues

EXPECTED_FILENAME = "expected_output.json"

_ASL_JSON = "_asl.json"
_M0_JSON = "_m0scan.json"
_TSV = "_aslcontext.tsv"
_NII_SUFFIXES = ("_asl.nii.gz", "_asl.nii")
_SKIP_DIRS = {"derivatives", "sourcedata"}


class ExampleStructureError(ValueError):
    """Raised when a case folder can't be turned into a valid call at all."""


class PairingFallbackWarning(UserWarning):
    """Emitted when an ASL is paired to an M0/TSV by fallback, not exact prefix."""


def _creation_time(path: Path) -> float:
    """Best-available creation time (birth time if present, else mtime).

    Linux lacks st_birthtime, and git does not preserve timestamps, so callers
    must tie-break by filename for determinism across clones.
    """
    st = path.stat()
    return float(getattr(st, "st_birthtime", st.st_mtime))


def _perf_dirs(case: Path) -> list[Path]:
    """Return raw-BIDS ``perf`` directories under a case, sorted by path."""
    out = []
    for d in case.rglob("perf"):
        if d.is_dir() and not _SKIP_DIRS.intersection(p.name for p in d.parents):
            out.append(d)
    return sorted(out)


def _prefix(name: str, suffix: str) -> str:
    """Strip a known modality suffix to get the shared BIDS entity prefix."""
    return name[: -len(suffix)]


def _categorize(
    perf: Path,
) -> tuple[dict[str, Path], dict[str, Path], dict[str, Path], dict[str, Path]]:
    """Index a perf dir's files by entity prefix, per modality.

    Returns:
        (asls, m0s, tsvs, niis) dicts mapping prefix -> path.

    Raises:
        ExampleStructureError: If two files in one modality share a prefix.
    """
    asls: dict[str, Path] = {}
    m0s: dict[str, Path] = {}
    tsvs: dict[str, Path] = {}
    niis: dict[str, Path] = {}

    def _put(bucket: dict[str, Path], key: str, path: Path, what: str) -> None:
        if key in bucket:
            raise ExampleStructureError(
                f"{perf}: two {what} files share prefix '{key}' "
                f"({bucket[key].name}, {path.name})"
            )
        bucket[key] = path

    for p in sorted(perf.iterdir()):
        n = p.name
        if n.endswith(_M0_JSON):
            _put(m0s, _prefix(n, _M0_JSON), p, "m0scan")
        elif n.endswith(_ASL_JSON):
            _put(asls, _prefix(n, _ASL_JSON), p, "asl.json")
        elif n.endswith(_TSV):
            _put(tsvs, _prefix(n, _TSV), p, "aslcontext.tsv")
        else:
            for suf in _NII_SUFFIXES:
                if n.endswith(suf):
                    _put(niis, _prefix(n, suf), p, "asl nifti")
                    break
    return asls, m0s, tsvs, niis


def _pair_sidecar(
    asl_prefixes: list[str], sidecars: dict[str, Path], kind: str, perf: Path
) -> dict[str, Optional[Path]]:
    """Map each ASL prefix to a sidecar, prefix-first then fallback.

    Fallback (used when an ASL has no exact-prefix sidecar) is the sidecar with the
    latest creation time, tie-broken by filename. This realises both mentor rules:
    reuse the shared M0 when there are more ASLs than M0s, and use the latest M0
    when there are more M0s than ASLs. Each fallback emits a warning.

    Args:
        asl_prefixes: Sorted ASL entity prefixes in this perf dir.
        sidecars: prefix -> path for one modality (m0scan or aslcontext.tsv).
        kind: Human label for messages ("m0scan" / "aslcontext.tsv").
        perf: The perf directory (for messages).

    Returns:
        prefix -> chosen sidecar path (or None if no sidecar of this kind exists).
    """
    if not sidecars:
        return {pre: None for pre in asl_prefixes}
    fallback = max(sidecars.values(), key=lambda p: (_creation_time(p), p.name))
    result: dict[str, Optional[Path]] = {}
    for pre in asl_prefixes:
        if pre in sidecars:
            result[pre] = sidecars[pre]
        else:
            result[pre] = fallback
            warnings.warn(
                f"{perf.name}: ASL '{pre}' has no prefix-matched {kind}; "
                f"reusing '{fallback.name}' (latest by creation time, then filename).",
                PairingFallbackWarning,
                stacklevel=2,
            )
    return result


# One acquisition: (asl, m0|None, tsv|None, nifti|None)
_Acq = tuple[Path, Optional[Path], Optional[Path], Optional[Path]]


def _collect_acquisitions(case: Path) -> list[_Acq]:
    """Gather ordered acquisitions across all perf dirs of a case.

    Raises:
        ExampleStructureError: If the case has no *_asl.json in any perf dir.
    """
    acquisitions: list[_Acq] = []
    for perf in _perf_dirs(case):
        asls, m0s, tsvs, niis = _categorize(perf)
        if not asls:
            continue
        prefixes = sorted(asls)
        m0_for = _pair_sidecar(prefixes, m0s, "m0scan", perf)
        tsv_for = _pair_sidecar(prefixes, tsvs, "aslcontext.tsv", perf)
        for pre in prefixes:
            acquisitions.append((asls[pre], m0_for[pre], tsv_for[pre], niis.get(pre)))
    if not acquisitions:
        raise ExampleStructureError(
            f"{case}: no *_asl.json found in any perf/ directory"
        )
    return acquisitions


def build_inputs(case: Path) -> tuple[list[str], str]:
    """Build the ordered (files, nifti_file) for a case's generate_report call.

    Files are emitted per acquisition as asl -> m0 -> tsv (load-bearing order). A
    single representative NIfTI is used (the tool records one slice count): the
    first *_asl.nii* in sorted order. Acquisitions may differ in geometry, so
    differing slice counts are allowed, not an error.

    Raises:
        ExampleStructureError: If the case has no ASL input or no ASL NIfTI.
    """
    acquisitions = _collect_acquisitions(case)

    files: list[str] = []
    for asl_path, m0_path, tsv_path, _ in acquisitions:
        files.append(str(asl_path))
        if m0_path is not None:
            files.append(str(m0_path))
        if tsv_path is not None:
            files.append(str(tsv_path))

    niftis = sorted(
        p
        for p in case.rglob("*asl.nii*")
        if "m0scan" not in p.name and not any(part in _SKIP_DIRS for part in p.parts)
    )
    if not niftis:
        raise ExampleStructureError(
            f"{case}: no *_asl.nii[.gz] found in any perf/ directory"
        )
    return files, str(niftis[0])


def discover_examples(base: Path) -> list[Path]:
    """Return case dirs under `base` (immediate children with a perf/*_asl.json).

    Keys on inputs, not on expected_output.json, so --update-expected can
    bootstrap a brand-new case. Missing/empty base yields [].
    """
    if not base.is_dir():
        return []
    cases = []
    for child in base.iterdir():
        if not child.is_dir():
            continue
        if any(
            p.name.endswith(_ASL_JSON)
            for perf in _perf_dirs(child)
            for p in perf.iterdir()
        ):
            cases.append(child)
    return sorted(cases)


def run_example(case: Path) -> dict[str, Any]:
    """Run the BIDS report path on one example case directory."""
    files, nifti = build_inputs(case)
    return generate_report(
        {
            "modality": ModalityTypeValues.ASL,
            "files": files,
            "nifti_file": nifti,
            "dcm_files": [],
        }
    )


def normalize(obj: Any) -> Any:
    """Round-trip through JSON so tuples (e.g. m0_parameters) compare as lists."""
    return json.loads(json.dumps(obj, default=str))


def load_expected(case: Path) -> dict[str, Any]:
    """Load and JSON-normalize a case's expected_output.json."""
    return normalize(json.loads((case / EXPECTED_FILENAME).read_text()))


def write_expected(case: Path, report: dict[str, Any]) -> None:
    """Overwrite a case's expected_output.json with `report` (golden update)."""
    (case / EXPECTED_FILENAME).write_text(
        json.dumps(report, indent=2, default=str) + "\n"
    )
